version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html/aws_codedeploy_demo
permissions:
   - object: /var/www/html/
     pattern: "**"
     mode: 644
     #mode: 755
     type:
       - file
hooks:
   AfterInstall:
    - location: scripts/restartapache.sh
      runas: root
