version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/npat
permissions:
   - object: /var/www/html/npat
     pattern: "**"
     mode: 775
     owner: root	
     group: root
     type:
       - directory
   - object: /var/www/html/npat
     pattern: "**"
     mode: 775
     owner: root	
     group: root
     type:
       - file
hooks:
  ValidateService:
    - location: scripts/startapache.sh
      timeout: 300
      runas: root
